package infuzion.chest.randomizer.storage;

import com.google.common.io.Files;
import infuzion.chest.randomizer.ChestRandomizer;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.scheduler.BukkitRunnable;
import org.bukkit.scheduler.BukkitTask;

import java.io.File;
import java.io.IOException;
import java.util.*;

@SuppressWarnings("unchecked")
public class fileChestManager extends chestManager {
    private final YamlConfiguration chestConfig;
    private final File chestConfigFile;
    private BukkitTask runnable;

    public fileChestManager(ChestRandomizer plugin) {
        super(plugin);
        chestConfigFile = new File(plugin.getDataFolder(), "chests.yml");
        chestConfig = YamlConfiguration.loadConfiguration(chestConfigFile);
        init();
    }

    private void backup() {
        if (plugin.getConfigManager().getBoolean("disableAutoBackup")) {
            return;
        }
        Calendar cal = Calendar.getInstance();
        long curTime = cal.getTimeInMillis();
        try {
            File directory = new File(chestConfigFile.getParentFile(), "backup");
            if (!directory.mkdir()) {
                return;
            }
            Files.copy(chestConfigFile, new File(directory, "chests_" + curTime + "_backup.yml"));
            File[] files = directory.listFiles();
            if (files == null) {
                return;
            }
            if (files.length > 25) {
                Arrays.sort(files, new Comparator<File>() {
                    public int compare(File f1, File f2) {
                        return -Long.valueOf(f1.lastModified()).compareTo(f2.lastModified());
                    }
                });

                for (int i = 24; i < files.length; i++) {
                    //noinspection ResultOfMethodCallIgnored
                    files[i].delete();
                }
            }

        } catch (IOException e) {
            plugin.getLogger().severe("chests.yml auto backup failed!");
        }
    }

    public void cleanUp() {
        if (runnable != null) {
            runnable.cancel();
        }
        save();
        saveFile(false);
    }

    void save() {
        Map<String, List<chestLocation>> groups = new HashMap<String, List<chestLocation>>();
        for (chestLocation e : chests) {
            String groupName = e.getGroup();
            List list;
            if (groups.containsKey(groupName)) {
                list = groups.get(groupName);
            } else {
                list = new ArrayList<chestLocation>();
            }

            list.add(e);
            groups.put(groupName, list);
        }

        for (String groupName : groups.keySet()) {
            chestConfig.set("ChestRandomizer." + groupName, groups.get(groupName));
        }
    }

    private void init() {
        chestConfig.options().header("DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING\n" +
                "Changes made can be deleted if the server is running\n" +
                "ANY ERRORS IN THE YML FORMAT CAN RESULT IN COMPLETE DESTRUCTION OF THIS FILE");
        chestConfig.addDefault("1", "1");
        chestConfig.options().copyDefaults(true);
        saveFile();
        load();
        backup();
        runnable = new BukkitRunnable() {
            public void run() {
                save();
                saveFile();
                backup();
            }
        }.runTaskTimer(plugin, 1200L, 1200);

    }

    private void load() {
        if (!chestConfig.isConfigurationSection("ChestRandomizer")) {
            return;
        }
        for (String groupName : chestConfig.getConfigurationSection("ChestRandomizer").getValues(false).keySet()) {
            for (chestLocation location : (List<chestLocation>) chestConfig.getList("ChestRandomizer." + groupName)) {
                chests.add(location);
            }
        }
    }

    private void saveFile() {
        saveFile(true);
    }

    private void saveFile(boolean async) {
        if (!async) {
            try {
                chestConfig.save(chestConfigFile);
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else {
            new BukkitRunnable() {
                public void run() {
                    saveFile(false);
                }
            }.runTaskAsynchronously(plugin);
        }
    }
}
